### ISSUE TITLE
Issue with Wireshark 3.4.6 :  Range is out of bounds

### ISSUE THREAD

**Issue by SylvainFloury** [128technology/128t-metadata-dissector#2]
Hello,
I installed the plugin on wireshark 3.4.6,  it is able to detect SVR Metadata, but it crashes when trying to inspect content.

For all SVR packet I have the following error message : 
Lua Error : C:\program Files\wireshark\128t_plugin.lua:91 Range is out of bounds.

In attachement a screenshot of the error in wireshark.  I can also provide a sample pcap.

Sylvain

![image](https://user-images.githubusercontent.com/85611653/121320329-5acbde00-c90d-11eb-9297-c729f900a95c.png)

**Comment by pemachado** [comment]
This kind of error should be reduced to a minimum by the 1.0.0 release.
This is still possible in some corner cases to which I have no easy fix but this should not be a big issue anymore.
Thanks for the report.
